services:
  - type: web
    name: livekit-server
    runtime: go
    buildCommand: |
      go build -o livekit ./cmd/server
      echo "APIkey_7k9mP2xQ8vN3wR5t: LKsec_9B4fH8jL2nM6pS1qW7eR3tY5uI0oA8" > keys.yaml
      echo "APIkey_3nV8bC4xF7mK9pL2: LKsec_6J9dN2vB5hG8kM3nQ7rT4wY1eP0sX" >> keys.yaml
    startCommand: ./livekit --config config.yaml --key-file keys.yaml
    envVars:
      - key: LIVEKIT_BIND
        value: "0.0.0.0"
      - key: LIVEKIT_LOG_LEVEL
        value: "info"
      - key: LIVEKIT_PORT
        value: "7880"
      - key: LIVEKIT_URL
        value: "wss://livekit-3ipj.onrender.com"
      - key: PORT
        value: "7880"
    healthCheckPath: /
    plan: starter # or standard/pro based on your needs
    
  # Optional: Add Redis for production scaling
  - type: redis
    name: livekit-redis
    plan: starter
    ipAllowList: []
